export const GET_USUARIOS = 'GET_USUARIOS';
export const GET_USUARIOS_SUCCESS = 'GET_USUARIOS_SUCCESS';
export const GET_USUARIOS_FAIL = 'GET_USUARIOS_FAIL';

export const SAVE_USUARIO = 'SAVE_USUARIO';
export const SAVE_USUARIO_SUCCESS = 'SAVE_USUARIO_SUCCESS';
export const SAVE_USUARIO_FAIL = 'SAVE_USUARIO_FAIL';

export const UPDATE_USUARIO = 'UPDATE_USUARIO';
export const UPDATE_USUARIO_SUCCESS = 'UPDATE_USUARIO_SUCCESS';
export const UPDATE_USUARIO_FAIL = 'UPDATE_USUARIO_FAIL';